# Generated by Django 2.1.3 on 2018-12-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='long',
            new_name='lon',
        ),
    ]
