# Generated by Django 2.1.3 on 2018-12-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20181207_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitutude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('user_id', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='dist',
            field=models.CharField(max_length=200),
        ),
    ]
